version: '3'

services:

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./../src:/var/www/html
            - ./server.conf:/etc/nginx/conf.d/server.conf

    php:
        image: library/php:5.6-fpm-alpine
        volumes:
            - ./../src:/var/www/html
        env_file:
            - .env